### ISSUE TITLE
Не собирается проект после обновления библиотек

### ISSUE THREAD

**Issue by tanya-rezo** [Harrix/static-site-webpack-habr#4]
После `git clone`, `npm install` и `npm run build` возникает ошибка сборки на версии e15abe7.

Окружение: Windows 10
Версии node:
```
node -v
v12.18.3
npm -v
6.14.6
```

<details>
  <summary>Вывод</summary>
  
  ```
  PS C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr> npm run build                                     
> static-site-webpack-habr@2.0.0 build C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr
> webpack --mode production && prettier --print-width=120 --parser html --write dist/*.html

Hash: 9ce7c4981fb2649792cc
Version: webpack 4.44.1
Time: 4867ms
Built at: 2020-09-13 19:38:50
 7 assets
Entrypoint main = ./js/bundle.js ./js/bundle.js.map
[2] multi ./src/js/index.js ./src/scss/style.scss 40 bytes {0} [built]
[3] ./src/js/index.js 167 bytes {0} [built]
[5] (webpack)/buildin/global.js 472 bytes {0} [built]
[6] ./src/scss/style.scss 1.2 KiB {0} [built] [failed] [1 error]
    + 3 hidden modules

ERROR in ./src/scss/style.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'plugins'. These properties are valid:
   object { postcssOptions?, execute?, sourceMap? }
    at validate (C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\postcss-loader\node_modules\schema-utils\dist\validate.js:98:11)
    at Object.loader (C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\postcss-loader\dist\index.js:43:28)
    at C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\webpack\lib\NormalModule.js:316:20
    at C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\loader-runner\lib\LoaderRunner.js:233:18
 @ multi ./src/js/index.js ./src/scss/style.scss main[1]
Child HtmlWebpackCompiler:
     2 assets
    Entrypoint HtmlWebpackPlugin_0 = __child-HtmlWebpackPlugin_0
    Entrypoint HtmlWebpackPlugin_1 = __child-HtmlWebpackPlugin_1
    [0] ./src/html/includes/header.html 468 bytes {0} {1} [built]
    [1] ./src/html/includes/footer.html 128 bytes {0} {1} [built]
    [2] ./node_modules/html-webpack-plugin/lib/loader.js!./src/html/views/index.html 737 bytes {0} [built]
    [3] ./node_modules/html-webpack-plugin/lib/loader.js!./src/html/views/second.html 750 bytes {1} [built]
Child mini-css-extract-plugin node_modules/css-loader/dist/cjs.js??ref--4-1!node_modules/postcss-loader/dist/cjs.js??postcss!node_modules/sass-loader/dist/cjs.js??ref--4-3!src/scss/style.scss:
    Entrypoint mini-css-extract-plugin = *
    [0] ./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js??ref--4-3!./src/scss/style.scss 695 bytes {0} [built] [failed] [1 error]

    ERROR in ./src/scss/style.scss (./node_modules/css-loader/dist/cjs.js??ref--4-1!./node_modules/postcss-loader/dist/cjs.js??postcss!./node_modules/sass-loader/dist/cjs.js??ref--4-3!./src/scss/style.scss)
    Module build failed (from ./node_modules/postcss-loader/dist/cjs.js):
    ValidationError: Invalid options object. PostCSS Loader has been initialized using an options object that does not match the API schema.
     - options has an unknown property 'plugins'. These properties are valid:
       object { postcssOptions?, execute?, sourceMap? }
        at validate (C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\postcss-loader\node_modules\schema-utils\dist\validate.js:98:11)
        at Object.loader (C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\postcss-loader\dist\index.js:43:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! static-site-webpack-habr@2.0.0 build: `webpack --mode production && prettier --print-width=120 --parser html --write dist/*.html`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the static-site-webpack-habr@2.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\antih\AppData\Roaming\npm-cache\_logs\2020-09-13T16_38_50_957Z-debug.log
  ```
  
</details>

<details>
  <summary>2020-09-13T16_38_50_957Z-debug.log</summary>
  
  ```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build'
1 verbose cli ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info lifecycle static-site-webpack-habr@2.0.0~prebuild: static-site-webpack-habr@2.0.0
6 info lifecycle static-site-webpack-habr@2.0.0~build: static-site-webpack-habr@2.0.0
7 verbose lifecycle static-site-webpack-habr@2.0.0~build: unsafe-perm in lifecycle true
8 verbose lifecycle static-site-webpack-habr@2.0.0~build: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\nodejs\;C:\Users\antih\AppData\Local\Microsoft\WindowsApps;C:\Users\antih\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\antih\AppData\Local\GitHubDesktop\bin;C:\Users\antih\AppData\Roaming\npm
9 verbose lifecycle static-site-webpack-habr@2.0.0~build: CWD: C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr
10 silly lifecycle static-site-webpack-habr@2.0.0~build: Args: [
10 silly lifecycle   '/d /s /c',
10 silly lifecycle   'webpack --mode production && prettier --print-width=120 --parser html --write dist/*.html'
10 silly lifecycle ]
11 silly lifecycle static-site-webpack-habr@2.0.0~build: Returned: code: 2  signal: null
12 info lifecycle static-site-webpack-habr@2.0.0~build: Failed to exec build script
13 verbose stack Error: static-site-webpack-habr@2.0.0 build: `webpack --mode production && prettier --print-width=120 --parser html --write dist/*.html`
13 verbose stack Exit status 2
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid static-site-webpack-habr@2.0.0
15 verbose cwd C:\Users\antih\OneDrive\Документы\GitHub\static-site-webpack-habr
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 2
22 error static-site-webpack-habr@2.0.0 build: `webpack --mode production && prettier --print-width=120 --parser html --write dist/*.html`
22 error Exit status 2
23 error Failed at the static-site-webpack-habr@2.0.0 build script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 2, true ]

  ```
  
</details>

**Comment by Harrix** [comment]
В коммите [Fix moments with PostCSS 4.0](https://github.com/Harrix/static-site-webpack-habr/commit/87772c02c4d558c5bd987eb9c1cd3651617bfdca) проблема решена.
